Bugfix/rdf bugfix
MolarVerse/PQAnalysis pull request #114
Opened 2024-12-11 17:45 UTC by stkroe

**Bug** in `rdf`
If not all optional keys are  defined in the input file, a `PQKeyError` occurs. But not all optional keys can be set simultaneously.

**Suggestion to solve it:**
- This was solved by include all not defined optional keys in the dictionary and set them at  `None`  in` RDFInputFileReader`  before the keys are actually used.
- Further, for the parsing also `NoneType`  in `_parse.py` the conditions for the `InputFileError` messages are changed so that `None` is not throwing an error anymore.

- The `rdf` program works only if a topology is given either with `restart_file` or (`moldescriptor_file` and `restart_file`).
If it is not given, an error occurs during the selection part of the target and reference molecules
Therefore, in `RDFInputFileReader` an error message was included.

- The `target_density` in `RDF`  was calculated:
```
target_density = len(self.target_index_combinations[0])
```
but this is only defined  if `no_intra_molecular=True`. So this was changed to:
```
        if self.no_intra_molecular:
            target_density = len(self.target_index_combinations[0])
        else:
            target_density = len(self.target_indices)
```
At the moment, no unexpected errors occur.

2024-12-11 22:49 UTC, 97gamjak commented
I really like the idea of introducing the "None" if I get it right. Could you provide a sample inputfile? And you execute it then just with `rdf <inpu>` or?

2024-12-12 09:15 UTC, stkroe commented
> I really like the idea of introducing the "None" if I get it right. Could you provide a sample inputfile? And you execute it then just with `rdf <input>` or?

Yes I just use `rdf <input>`  and no further errors have been found so far.

The input file looks like:

```
reference_selection = H
target_selection = H
delta_r = 0.05
out_file = rdf_test.out
restart_file = md-test.rst
traj_files = test.xyz
```

2024-12-16 21:07 UTC, 97gamjak requested changes

2024-12-23 20:59 UTC, galjos commented
The tests are blocked most likely due to a numpy function `numpy.atleast_1d` in `Trajectory.__init__()`. I have the same issue on mac. Removing it could resolve this one.

2025-01-10 22:11 UTC, 97gamjak commented
Does it now work also for plain `.xyz` files?

2025-01-13 08:38 UTC, stkroe commented
``> Does it now work also for plain `.xyz` files?

I changed the topology definition in the `rdf.py`:

` if traj.topology is not None:
            self.topology = traj.topology
        else:
            self.topology = self.first_frame.topology
`

Now it is working without throwing an error and the comparison with restart file topology gives the same rdf results.

2026-06-08 20:27 UTC, merged